ui <- navbarPage(
  "Interactivity examples",
  
  ################################################################################
  tabPanel("Example 1: Static",
           # Note that the 'data_age' object has been created in global.R and is accessible in ui.R
           data_age %$%
             paste0(Age,": ",Headcount) %>%
             paste0(collapse="<br>") %>%
             paste0("In 2023, the number of Civil Servants by age group was:<br>",.) %>%
             HTML()
           ),
  
  ################################################################################
  tabPanel("Example 2: Generating graphs",
           # Note that the 'age_graph' object assigned to 'output' in server is available here
           plotOutput("age_graph")),
  
  
  ################################################################################
  tabPanel("Example 3: User input",
           # Include a UI element that will allow the selection of a variable
           # Note the first argument, the 'inputId' which is the name that will be used to access the value of this element in the server code
           selectInput("variable_selection_ex3",label="Choose a variable",choices=c("Age","Disability"),selected="Age"),
           br(),
           # Display the resulting graph
           plotOutput("var_graph_ex3")),
  
  ################################################################################
  tabPanel("Example 4: Dynamic UI",
           # In the same way that graphs or tables are generated by the server, UI elements can be made as well
           # The UI element is defined in the server and given an outputID, which is then called here
           uiOutput("ui_variable_selection_ex4"),
           br(),
           # Display the resulting graph
           plotOutput("var_graph_ex4")),
  
  ################################################################################
  tabPanel("Example 5: Reactive functions",
           # We can also define 'reactive functions' in the code to simplify
           # UI element as before
           uiOutput("ui_variable_selection_ex5"),
           br(),
           # Display the resulting graph
           plotOutput("var_graph_ex5"),
           # Also show as a table
           tableOutput("var_table_ex5")),
  
  ################################################################################
  tabPanel("The end",
           "Any questions?")
)
